ARG GOLANG_VERSION=1.24
FROM golang:${GOLANG_VERSION}-bullseye

RUN apt-get update && \
    apt-get install -y gcc make gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu \
    && rm -rf /var/lib/apt/lists/*
