name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Enables manual trigger
  
jobs:

  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.6.1
      
    - name: Login to Oracle Cloud Infrastructure Registry (OCIR)
      run: |
        echo "${{ secrets.OCIR_AUTH_TOKEN }}" | docker login -u "${{ secrets.OCIR_NAMESPACE }}/${{ secrets.OCIR_USER_MAIL }}" ${{ secrets.OCI_REGION }}.ocir.io --password-stdin     

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/arm64
        context: app
        file: app/Dockerfile
        tags: ${{ secrets.OCI_REGION }}.ocir.io/${{ secrets.OCIR_NAMESPACE }}/${{ secrets.NAME_REPO }}/krakend:$(date +%s)
        push: false
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max   
        
    - name: Push Docker Image to Oracle Cloud Registry
      run: |
        docker push ${{ secrets.OCI_REGION }}.ocir.io/${{ secrets.OCIR_NAMESPACE }}/${{ secrets.NAME_REPO }}/krakend:$(date +%s) 
    
